// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: controller/controller.proto

package controller

import (
	proto "github.com/9triver/ignis/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_UNSPECIFIED                CommandType = 0 // unknown command type
	CommandType_ACK                        CommandType = 1 // acknowledged
	CommandType_FR_READY                   CommandType = 2
	CommandType_FR_APPEND_DATA             CommandType = 3 // frontend: append data node
	CommandType_FR_APPEND_GO               CommandType = 4 // front: append actor (for debugging purpose)
	CommandType_FR_APPEND_PY_FUNC          CommandType = 5 // frontend: append python function (control node definition)
	CommandType_FR_APPEND_PY_CLASS         CommandType = 6 // frontend: append python class (control node definition)
	CommandType_FR_APPEND_UNIKERNEL        CommandType = 7
	CommandType_FR_APPEND_ARG              CommandType = 8 // frontend: append function arg to specified actor
	CommandType_FR_APPEND_CLASS_METHOD_ARG CommandType = 9 // frontend: append class method arg to specified actor
	CommandType_FR_INVOKE                  CommandType = 10
	CommandType_BK_RETURN_RESULT           CommandType = 11 // backend: send back execution result
	CommandType_FR_REGISTER_REQUEST        CommandType = 12 // backend: register application
	CommandType_FR_DAG                     CommandType = 13 // frontend: send DAG structure
	CommandType_FR_MARK_DAG_NODE_DONE      CommandType = 14 // frontend: notify DAG node done
	CommandType_FR_REQUEST_OBJECT          CommandType = 15 // frontend: request object from object store
	CommandType_BK_RESPONSE_OBJECT         CommandType = 16 // backend: response object to request object
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "ACK",
		2:  "FR_READY",
		3:  "FR_APPEND_DATA",
		4:  "FR_APPEND_GO",
		5:  "FR_APPEND_PY_FUNC",
		6:  "FR_APPEND_PY_CLASS",
		7:  "FR_APPEND_UNIKERNEL",
		8:  "FR_APPEND_ARG",
		9:  "FR_APPEND_CLASS_METHOD_ARG",
		10: "FR_INVOKE",
		11: "BK_RETURN_RESULT",
		12: "FR_REGISTER_REQUEST",
		13: "FR_DAG",
		14: "FR_MARK_DAG_NODE_DONE",
		15: "FR_REQUEST_OBJECT",
		16: "BK_RESPONSE_OBJECT",
	}
	CommandType_value = map[string]int32{
		"UNSPECIFIED":                0,
		"ACK":                        1,
		"FR_READY":                   2,
		"FR_APPEND_DATA":             3,
		"FR_APPEND_GO":               4,
		"FR_APPEND_PY_FUNC":          5,
		"FR_APPEND_PY_CLASS":         6,
		"FR_APPEND_UNIKERNEL":        7,
		"FR_APPEND_ARG":              8,
		"FR_APPEND_CLASS_METHOD_ARG": 9,
		"FR_INVOKE":                  10,
		"BK_RETURN_RESULT":           11,
		"FR_REGISTER_REQUEST":        12,
		"FR_DAG":                     13,
		"FR_MARK_DAG_NODE_DONE":      14,
		"FR_REQUEST_OBJECT":          15,
		"BK_RESPONSE_OBJECT":         16,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_controller_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_controller_controller_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{0}
}

type Data_ObjectType int32

const (
	Data_OBJ_UNSPECIFIED Data_ObjectType = 0
	Data_OBJ_REF         Data_ObjectType = 1
	Data_OBJ_ENCODED     Data_ObjectType = 2
	Data_OBJ_STREAM      Data_ObjectType = 3
)

// Enum value maps for Data_ObjectType.
var (
	Data_ObjectType_name = map[int32]string{
		0: "OBJ_UNSPECIFIED",
		1: "OBJ_REF",
		2: "OBJ_ENCODED",
		3: "OBJ_STREAM",
	}
	Data_ObjectType_value = map[string]int32{
		"OBJ_UNSPECIFIED": 0,
		"OBJ_REF":         1,
		"OBJ_ENCODED":     2,
		"OBJ_STREAM":      3,
	}
)

func (x Data_ObjectType) Enum() *Data_ObjectType {
	p := new(Data_ObjectType)
	*p = x
	return p
}

func (x Data_ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_controller_proto_enumTypes[1].Descriptor()
}

func (Data_ObjectType) Type() protoreflect.EnumType {
	return &file_controller_controller_proto_enumTypes[1]
}

func (x Data_ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Data_ObjectType.Descriptor instead.
func (Data_ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{2, 0}
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_controller_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{0}
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_controller_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{1}
}

type Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Data_ObjectType        `protobuf:"varint,1,opt,name=Type,proto3,enum=controller.Data_ObjectType" json:"Type,omitempty"`
	// Types that are valid to be assigned to Object:
	//
	//	*Data_Ref
	//	*Data_Encoded
	Object        isData_Object `protobuf_oneof:"Object"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_controller_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetType() Data_ObjectType {
	if x != nil {
		return x.Type
	}
	return Data_OBJ_UNSPECIFIED
}

func (x *Data) GetObject() isData_Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Data) GetRef() *proto.Flow {
	if x != nil {
		if x, ok := x.Object.(*Data_Ref); ok {
			return x.Ref
		}
	}
	return nil
}

func (x *Data) GetEncoded() *proto.EncodedObject {
	if x != nil {
		if x, ok := x.Object.(*Data_Encoded); ok {
			return x.Encoded
		}
	}
	return nil
}

type isData_Object interface {
	isData_Object()
}

type Data_Ref struct {
	Ref *proto.Flow `protobuf:"bytes,2,opt,name=Ref,proto3,oneof"`
}

type Data_Encoded struct {
	Encoded *proto.EncodedObject `protobuf:"bytes,3,opt,name=Encoded,proto3,oneof"`
}

func (*Data_Ref) isData_Object() {}

func (*Data_Encoded) isData_Object() {}

type AppendData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"` // current execution session, empty if shared by all sessions
	Object        *proto.EncodedObject   `protobuf:"bytes,2,opt,name=Object,proto3" json:"Object,omitempty"`       // encoded object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendData) Reset() {
	*x = AppendData{}
	mi := &file_controller_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendData) ProtoMessage() {}

func (x *AppendData) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendData.ProtoReflect.Descriptor instead.
func (*AppendData) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{3}
}

func (x *AppendData) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *AppendData) GetObject() *proto.EncodedObject {
	if x != nil {
		return x.Object
	}
	return nil
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CPU           int64                  `protobuf:"varint,1,opt,name=CPU,proto3" json:"CPU,omitempty"`       // CPU cores
	Memory        int64                  `protobuf:"varint,2,opt,name=Memory,proto3" json:"Memory,omitempty"` // memory in Bytes
	GPU           int64                  `protobuf:"varint,3,opt,name=GPU,proto3" json:"GPU,omitempty"`       // GPU cores
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_controller_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{4}
}

func (x *Resources) GetCPU() int64 {
	if x != nil {
		return x.CPU
	}
	return 0
}

func (x *Resources) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Resources) GetGPU() int64 {
	if x != nil {
		return x.GPU
	}
	return 0
}

type AppendPyFunc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`                              // function name
	Params        []string               `protobuf:"bytes,2,rep,name=Params,proto3" json:"Params,omitempty"`                          //function params
	Venv          string                 `protobuf:"bytes,3,opt,name=Venv,proto3" json:"Venv,omitempty"`                              // function virtual environment
	Requirements  []string               `protobuf:"bytes,4,rep,name=Requirements,proto3" json:"Requirements,omitempty"`              // function dependencies
	PickledObject []byte                 `protobuf:"bytes,5,opt,name=PickledObject,proto3" json:"PickledObject,omitempty"`            // encoded function impl
	Language      proto.Language         `protobuf:"varint,6,opt,name=Language,proto3,enum=proto.Language" json:"Language,omitempty"` // return type of function
	Resources     *Resources             `protobuf:"bytes,7,opt,name=Resources,proto3" json:"Resources,omitempty"`                    // resources required by function
	Replicas      int32                  `protobuf:"varint,8,opt,name=Replicas,proto3" json:"Replicas,omitempty"`                     // number of replicas
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPyFunc) Reset() {
	*x = AppendPyFunc{}
	mi := &file_controller_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPyFunc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPyFunc) ProtoMessage() {}

func (x *AppendPyFunc) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPyFunc.ProtoReflect.Descriptor instead.
func (*AppendPyFunc) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{5}
}

func (x *AppendPyFunc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppendPyFunc) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AppendPyFunc) GetVenv() string {
	if x != nil {
		return x.Venv
	}
	return ""
}

func (x *AppendPyFunc) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *AppendPyFunc) GetPickledObject() []byte {
	if x != nil {
		return x.PickledObject
	}
	return nil
}

func (x *AppendPyFunc) GetLanguage() proto.Language {
	if x != nil {
		return x.Language
	}
	return proto.Language(0)
}

func (x *AppendPyFunc) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AppendPyFunc) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type AppendPyClass struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Name          string                       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // class name
	Methods       []*AppendPyClass_ClassMethod `protobuf:"bytes,2,rep,name=Methods,proto3" json:"Methods,omitempty"`
	Venv          string                       `protobuf:"bytes,3,opt,name=Venv,proto3" json:"Venv,omitempty"`                              // function virtual environment
	Requirements  []string                     `protobuf:"bytes,4,rep,name=Requirements,proto3" json:"Requirements,omitempty"`              // function dependencies
	PickledObject []byte                       `protobuf:"bytes,5,opt,name=PickledObject,proto3" json:"PickledObject,omitempty"`            // encoded function impl
	Language      proto.Language               `protobuf:"varint,6,opt,name=Language,proto3,enum=proto.Language" json:"Language,omitempty"` // return type of function
	Resources     *Resources                   `protobuf:"bytes,7,opt,name=Resources,proto3" json:"Resources,omitempty"`                    // resources required by class
	Replicas      int32                        `protobuf:"varint,8,opt,name=Replicas,proto3" json:"Replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPyClass) Reset() {
	*x = AppendPyClass{}
	mi := &file_controller_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPyClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPyClass) ProtoMessage() {}

func (x *AppendPyClass) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPyClass.ProtoReflect.Descriptor instead.
func (*AppendPyClass) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{6}
}

func (x *AppendPyClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppendPyClass) GetMethods() []*AppendPyClass_ClassMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *AppendPyClass) GetVenv() string {
	if x != nil {
		return x.Venv
	}
	return ""
}

func (x *AppendPyClass) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *AppendPyClass) GetPickledObject() []byte {
	if x != nil {
		return x.PickledObject
	}
	return nil
}

func (x *AppendPyClass) GetLanguage() proto.Language {
	if x != nil {
		return x.Language
	}
	return proto.Language(0)
}

func (x *AppendPyClass) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AppendPyClass) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type AppendGo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`     // function name
	Params        []string               `protobuf:"bytes,2,rep,name=Params,proto3" json:"Params,omitempty"` // function params
	Code          string                 `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Language      proto.Language         `protobuf:"varint,4,opt,name=Language,proto3,enum=proto.Language" json:"Language,omitempty"` // return type of function
	Resources     *Resources             `protobuf:"bytes,5,opt,name=Resources,proto3" json:"Resources,omitempty"`                    // resources required by class
	Replicas      int32                  `protobuf:"varint,6,opt,name=Replicas,proto3" json:"Replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendGo) Reset() {
	*x = AppendGo{}
	mi := &file_controller_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendGo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendGo) ProtoMessage() {}

func (x *AppendGo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendGo.ProtoReflect.Descriptor instead.
func (*AppendGo) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{7}
}

func (x *AppendGo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppendGo) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AppendGo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AppendGo) GetLanguage() proto.Language {
	if x != nil {
		return x.Language
	}
	return proto.Language(0)
}

func (x *AppendGo) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AppendGo) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type AppendUnikernel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`                              // function name
	Params        []string               `protobuf:"bytes,2,rep,name=Params,proto3" json:"Params,omitempty"`                          // function params
	Unikernel     string                 `protobuf:"bytes,3,opt,name=Unikernel,proto3" json:"Unikernel,omitempty"`                    // content of unikernel.ml
	Language      proto.Language         `protobuf:"varint,4,opt,name=Language,proto3,enum=proto.Language" json:"Language,omitempty"` // return type of function
	Resources     *Resources             `protobuf:"bytes,5,opt,name=Resources,proto3" json:"Resources,omitempty"`                    // resources required by class
	Replicas      int32                  `protobuf:"varint,6,opt,name=Replicas,proto3" json:"Replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendUnikernel) Reset() {
	*x = AppendUnikernel{}
	mi := &file_controller_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendUnikernel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendUnikernel) ProtoMessage() {}

func (x *AppendUnikernel) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendUnikernel.ProtoReflect.Descriptor instead.
func (*AppendUnikernel) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{8}
}

func (x *AppendUnikernel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppendUnikernel) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AppendUnikernel) GetUnikernel() string {
	if x != nil {
		return x.Unikernel
	}
	return ""
}

func (x *AppendUnikernel) GetLanguage() proto.Language {
	if x != nil {
		return x.Language
	}
	return proto.Language(0)
}

func (x *AppendUnikernel) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AppendUnikernel) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type AppendArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`   // current execution session
	InstanceID    string                 `protobuf:"bytes,2,opt,name=InstanceID,proto3" json:"InstanceID,omitempty"` // id of function instance under current execution session
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`             // function name
	Param         string                 `protobuf:"bytes,4,opt,name=Param,proto3" json:"Param,omitempty"`           // param name
	Value         *Data                  `protobuf:"bytes,5,opt,name=Value,proto3" json:"Value,omitempty"`           // object ref for param
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendArg) Reset() {
	*x = AppendArg{}
	mi := &file_controller_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendArg) ProtoMessage() {}

func (x *AppendArg) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendArg.ProtoReflect.Descriptor instead.
func (*AppendArg) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{9}
}

func (x *AppendArg) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *AppendArg) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *AppendArg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppendArg) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *AppendArg) GetValue() *Data {
	if x != nil {
		return x.Value
	}
	return nil
}

type AppendClassMethodArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`   // current execution session
	InstanceID    string                 `protobuf:"bytes,2,opt,name=InstanceID,proto3" json:"InstanceID,omitempty"` // id of **class** instance under current execution session
	MethodName    string                 `protobuf:"bytes,3,opt,name=MethodName,proto3" json:"MethodName,omitempty"` // method name
	Param         string                 `protobuf:"bytes,4,opt,name=Param,proto3" json:"Param,omitempty"`           // param name
	Value         *Data                  `protobuf:"bytes,5,opt,name=Value,proto3" json:"Value,omitempty"`           // object ref for param
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendClassMethodArg) Reset() {
	*x = AppendClassMethodArg{}
	mi := &file_controller_controller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendClassMethodArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendClassMethodArg) ProtoMessage() {}

func (x *AppendClassMethodArg) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendClassMethodArg.ProtoReflect.Descriptor instead.
func (*AppendClassMethodArg) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{10}
}

func (x *AppendClassMethodArg) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *AppendClassMethodArg) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *AppendClassMethodArg) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *AppendClassMethodArg) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *AppendClassMethodArg) GetValue() *Data {
	if x != nil {
		return x.Value
	}
	return nil
}

type Invoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`   // current execution session
	InstanceID    string                 `protobuf:"bytes,2,opt,name=InstanceID,proto3" json:"InstanceID,omitempty"` // id of function instance under current execution session
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`             // function name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoke) Reset() {
	*x = Invoke{}
	mi := &file_controller_controller_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoke) ProtoMessage() {}

func (x *Invoke) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoke.ProtoReflect.Descriptor instead.
func (*Invoke) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{11}
}

func (x *Invoke) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *Invoke) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *Invoke) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReturnResult struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SessionID  string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`   // current execution session
	InstanceID string                 `protobuf:"bytes,2,opt,name=InstanceID,proto3" json:"InstanceID,omitempty"` // id of function instance under current execution session
	Name       string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`             // function name
	// Types that are valid to be assigned to Result:
	//
	//	*ReturnResult_Value
	//	*ReturnResult_Error
	Result        isReturnResult_Result `protobuf_oneof:"Result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnResult) Reset() {
	*x = ReturnResult{}
	mi := &file_controller_controller_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnResult) ProtoMessage() {}

func (x *ReturnResult) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnResult.ProtoReflect.Descriptor instead.
func (*ReturnResult) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{12}
}

func (x *ReturnResult) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *ReturnResult) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *ReturnResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReturnResult) GetResult() isReturnResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReturnResult) GetValue() *Data {
	if x != nil {
		if x, ok := x.Result.(*ReturnResult_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *ReturnResult) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ReturnResult_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isReturnResult_Result interface {
	isReturnResult_Result()
}

type ReturnResult_Value struct {
	Value *Data `protobuf:"bytes,4,opt,name=Value,proto3,oneof"` // success: return result
}

type ReturnResult_Error struct {
	Error string `protobuf:"bytes,5,opt,name=Error,proto3,oneof"` // fail: return error
}

func (*ReturnResult_Value) isReturnResult_Result() {}

func (*ReturnResult_Error) isReturnResult_Result() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationID string                 `protobuf:"bytes,1,opt,name=ApplicationID,proto3" json:"ApplicationID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_controller_controller_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterRequest) GetApplicationID() string {
	if x != nil {
		return x.ApplicationID
	}
	return ""
}

// DAG Node Messages
type ControlNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=Done,proto3" json:"Done,omitempty"`
	FunctionName  string                 `protobuf:"bytes,3,opt,name=FunctionName,proto3" json:"FunctionName,omitempty"`
	Params        map[string]string      `protobuf:"bytes,4,rep,name=Params,proto3" json:"Params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // lambda_id -> parameter_name mapping
	Current       int32                  `protobuf:"varint,5,opt,name=Current,proto3" json:"Current,omitempty"`
	DataNode      string                 `protobuf:"bytes,6,opt,name=DataNode,proto3" json:"DataNode,omitempty"`         // id of the output data node
	PreDataNodes  []string               `protobuf:"bytes,7,rep,name=PreDataNodes,proto3" json:"PreDataNodes,omitempty"` // ids of input data nodes
	FunctionType  string                 `protobuf:"bytes,8,opt,name=FunctionType,proto3" json:"FunctionType,omitempty"` // "remote" or "local"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlNode) Reset() {
	*x = ControlNode{}
	mi := &file_controller_controller_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlNode) ProtoMessage() {}

func (x *ControlNode) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlNode.ProtoReflect.Descriptor instead.
func (*ControlNode) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{14}
}

func (x *ControlNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ControlNode) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ControlNode) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ControlNode) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ControlNode) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ControlNode) GetDataNode() string {
	if x != nil {
		return x.DataNode
	}
	return ""
}

func (x *ControlNode) GetPreDataNodes() []string {
	if x != nil {
		return x.PreDataNodes
	}
	return nil
}

func (x *ControlNode) GetFunctionType() string {
	if x != nil {
		return x.FunctionType
	}
	return ""
}

type DataNode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Done            bool                   `protobuf:"varint,2,opt,name=Done,proto3" json:"Done,omitempty"`
	Lambda          string                 `protobuf:"bytes,3,opt,name=Lambda,proto3" json:"Lambda,omitempty"` // lambda id
	Ready           bool                   `protobuf:"varint,4,opt,name=Ready,proto3" json:"Ready,omitempty"`
	SufControlNodes []string               `protobuf:"bytes,5,rep,name=SufControlNodes,proto3" json:"SufControlNodes,omitempty"`     // ids of successor control nodes
	PreControlNode  *string                `protobuf:"bytes,6,opt,name=PreControlNode,proto3,oneof" json:"PreControlNode,omitempty"` // id of predecessor control node (nullable)
	ParentNode      *string                `protobuf:"bytes,7,opt,name=ParentNode,proto3,oneof" json:"ParentNode,omitempty"`         // id of parent data node (nullable)
	ChildNode       []string               `protobuf:"bytes,8,rep,name=ChildNode,proto3" json:"ChildNode,omitempty"`                 // ids of child data nodes
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DataNode) Reset() {
	*x = DataNode{}
	mi := &file_controller_controller_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataNode) ProtoMessage() {}

func (x *DataNode) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataNode.ProtoReflect.Descriptor instead.
func (*DataNode) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{15}
}

func (x *DataNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataNode) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *DataNode) GetLambda() string {
	if x != nil {
		return x.Lambda
	}
	return ""
}

func (x *DataNode) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *DataNode) GetSufControlNodes() []string {
	if x != nil {
		return x.SufControlNodes
	}
	return nil
}

func (x *DataNode) GetPreControlNode() string {
	if x != nil && x.PreControlNode != nil {
		return *x.PreControlNode
	}
	return ""
}

func (x *DataNode) GetParentNode() string {
	if x != nil && x.ParentNode != nil {
		return *x.ParentNode
	}
	return ""
}

func (x *DataNode) GetChildNode() []string {
	if x != nil {
		return x.ChildNode
	}
	return nil
}

type DAGNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"` // "ControlNode" or "DataNode"
	// Types that are valid to be assigned to Node:
	//
	//	*DAGNode_ControlNode
	//	*DAGNode_DataNode
	Node          isDAGNode_Node `protobuf_oneof:"Node"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAGNode) Reset() {
	*x = DAGNode{}
	mi := &file_controller_controller_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAGNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGNode) ProtoMessage() {}

func (x *DAGNode) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGNode.ProtoReflect.Descriptor instead.
func (*DAGNode) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{16}
}

func (x *DAGNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DAGNode) GetNode() isDAGNode_Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *DAGNode) GetControlNode() *ControlNode {
	if x != nil {
		if x, ok := x.Node.(*DAGNode_ControlNode); ok {
			return x.ControlNode
		}
	}
	return nil
}

func (x *DAGNode) GetDataNode() *DataNode {
	if x != nil {
		if x, ok := x.Node.(*DAGNode_DataNode); ok {
			return x.DataNode
		}
	}
	return nil
}

type isDAGNode_Node interface {
	isDAGNode_Node()
}

type DAGNode_ControlNode struct {
	ControlNode *ControlNode `protobuf:"bytes,2,opt,name=ControlNode,proto3,oneof"`
}

type DAGNode_DataNode struct {
	DataNode *DataNode `protobuf:"bytes,3,opt,name=DataNode,proto3,oneof"`
}

func (*DAGNode_ControlNode) isDAGNode_Node() {}

func (*DAGNode_DataNode) isDAGNode_Node() {}

type DAG struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*DAGNode             `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAG) Reset() {
	*x = DAG{}
	mi := &file_controller_controller_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAG) ProtoMessage() {}

func (x *DAG) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAG.ProtoReflect.Descriptor instead.
func (*DAG) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{17}
}

func (x *DAG) GetNodes() []*DAGNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type MarkDAGNodeDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkDAGNodeDone) Reset() {
	*x = MarkDAGNodeDone{}
	mi := &file_controller_controller_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkDAGNodeDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkDAGNodeDone) ProtoMessage() {}

func (x *MarkDAGNodeDone) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkDAGNodeDone.ProtoReflect.Descriptor instead.
func (*MarkDAGNodeDone) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{18}
}

func (x *MarkDAGNodeDone) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MarkDAGNodeDone) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RequestObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestObject) Reset() {
	*x = RequestObject{}
	mi := &file_controller_controller_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestObject) ProtoMessage() {}

func (x *RequestObject) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestObject.ProtoReflect.Descriptor instead.
func (*RequestObject) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{19}
}

func (x *RequestObject) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RequestObject) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type ResponseObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Value         *proto.EncodedObject   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseObject) Reset() {
	*x = ResponseObject{}
	mi := &file_controller_controller_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseObject) ProtoMessage() {}

func (x *ResponseObject) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseObject.ProtoReflect.Descriptor instead.
func (*ResponseObject) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{20}
}

func (x *ResponseObject) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ResponseObject) GetValue() *proto.EncodedObject {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ResponseObject) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  CommandType            `protobuf:"varint,1,opt,name=Type,proto3,enum=controller.CommandType" json:"Type,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*Message_Ack
	//	*Message_Ready
	//	*Message_AppendData
	//	*Message_AppendGo
	//	*Message_AppendPyFunc
	//	*Message_AppendPyClass
	//	*Message_AppendUnikernel
	//	*Message_AppendArg
	//	*Message_AppendClassMethodArg
	//	*Message_Invoke
	//	*Message_ReturnResult
	//	*Message_RegisterRequest
	//	*Message_DAG
	//	*Message_MarkDAGNodeDone
	//	*Message_RequestObject
	//	*Message_ResponseObject
	Command       isMessage_Command `protobuf_oneof:"Command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_controller_controller_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{21}
}

func (x *Message) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_UNSPECIFIED
}

func (x *Message) GetCommand() isMessage_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Message) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Command.(*Message_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Message) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Command.(*Message_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *Message) GetAppendData() *AppendData {
	if x != nil {
		if x, ok := x.Command.(*Message_AppendData); ok {
			return x.AppendData
		}
	}
	return nil
}

func (x *Message) GetAppendGo() *AppendGo {
	if x != nil {
		if x, ok := x.Command.(*Message_AppendGo); ok {
			return x.AppendGo
		}
	}
	return nil
}

func (x *Message) GetAppendPyFunc() *AppendPyFunc {
	if x != nil {
		if x, ok := x.Command.(*Message_AppendPyFunc); ok {
			return x.AppendPyFunc
		}
	}
	return nil
}

func (x *Message) GetAppendPyClass() *AppendPyClass {
	if x != nil {
		if x, ok := x.Command.(*Message_AppendPyClass); ok {
			return x.AppendPyClass
		}
	}
	return nil
}

func (x *Message) GetAppendUnikernel() *AppendUnikernel {
	if x != nil {
		if x, ok := x.Command.(*Message_AppendUnikernel); ok {
			return x.AppendUnikernel
		}
	}
	return nil
}

func (x *Message) GetAppendArg() *AppendArg {
	if x != nil {
		if x, ok := x.Command.(*Message_AppendArg); ok {
			return x.AppendArg
		}
	}
	return nil
}

func (x *Message) GetAppendClassMethodArg() *AppendClassMethodArg {
	if x != nil {
		if x, ok := x.Command.(*Message_AppendClassMethodArg); ok {
			return x.AppendClassMethodArg
		}
	}
	return nil
}

func (x *Message) GetInvoke() *Invoke {
	if x != nil {
		if x, ok := x.Command.(*Message_Invoke); ok {
			return x.Invoke
		}
	}
	return nil
}

func (x *Message) GetReturnResult() *ReturnResult {
	if x != nil {
		if x, ok := x.Command.(*Message_ReturnResult); ok {
			return x.ReturnResult
		}
	}
	return nil
}

func (x *Message) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Command.(*Message_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Message) GetDAG() *DAG {
	if x != nil {
		if x, ok := x.Command.(*Message_DAG); ok {
			return x.DAG
		}
	}
	return nil
}

func (x *Message) GetMarkDAGNodeDone() *MarkDAGNodeDone {
	if x != nil {
		if x, ok := x.Command.(*Message_MarkDAGNodeDone); ok {
			return x.MarkDAGNodeDone
		}
	}
	return nil
}

func (x *Message) GetRequestObject() *RequestObject {
	if x != nil {
		if x, ok := x.Command.(*Message_RequestObject); ok {
			return x.RequestObject
		}
	}
	return nil
}

func (x *Message) GetResponseObject() *ResponseObject {
	if x != nil {
		if x, ok := x.Command.(*Message_ResponseObject); ok {
			return x.ResponseObject
		}
	}
	return nil
}

type isMessage_Command interface {
	isMessage_Command()
}

type Message_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=Ack,proto3,oneof"`
}

type Message_Ready struct {
	Ready *Ready `protobuf:"bytes,3,opt,name=Ready,proto3,oneof"`
}

type Message_AppendData struct {
	AppendData *AppendData `protobuf:"bytes,4,opt,name=AppendData,proto3,oneof"`
}

type Message_AppendGo struct {
	AppendGo *AppendGo `protobuf:"bytes,5,opt,name=AppendGo,proto3,oneof"`
}

type Message_AppendPyFunc struct {
	AppendPyFunc *AppendPyFunc `protobuf:"bytes,6,opt,name=AppendPyFunc,proto3,oneof"`
}

type Message_AppendPyClass struct {
	AppendPyClass *AppendPyClass `protobuf:"bytes,7,opt,name=AppendPyClass,proto3,oneof"`
}

type Message_AppendUnikernel struct {
	AppendUnikernel *AppendUnikernel `protobuf:"bytes,8,opt,name=AppendUnikernel,proto3,oneof"`
}

type Message_AppendArg struct {
	AppendArg *AppendArg `protobuf:"bytes,9,opt,name=AppendArg,proto3,oneof"`
}

type Message_AppendClassMethodArg struct {
	AppendClassMethodArg *AppendClassMethodArg `protobuf:"bytes,10,opt,name=AppendClassMethodArg,proto3,oneof"`
}

type Message_Invoke struct {
	Invoke *Invoke `protobuf:"bytes,11,opt,name=Invoke,proto3,oneof"`
}

type Message_ReturnResult struct {
	ReturnResult *ReturnResult `protobuf:"bytes,12,opt,name=ReturnResult,proto3,oneof"`
}

type Message_RegisterRequest struct {
	RegisterRequest *RegisterRequest `protobuf:"bytes,13,opt,name=RegisterRequest,proto3,oneof"`
}

type Message_DAG struct {
	DAG *DAG `protobuf:"bytes,14,opt,name=DAG,proto3,oneof"`
}

type Message_MarkDAGNodeDone struct {
	MarkDAGNodeDone *MarkDAGNodeDone `protobuf:"bytes,15,opt,name=MarkDAGNodeDone,proto3,oneof"`
}

type Message_RequestObject struct {
	RequestObject *RequestObject `protobuf:"bytes,16,opt,name=RequestObject,proto3,oneof"`
}

type Message_ResponseObject struct {
	ResponseObject *ResponseObject `protobuf:"bytes,17,opt,name=ResponseObject,proto3,oneof"`
}

func (*Message_Ack) isMessage_Command() {}

func (*Message_Ready) isMessage_Command() {}

func (*Message_AppendData) isMessage_Command() {}

func (*Message_AppendGo) isMessage_Command() {}

func (*Message_AppendPyFunc) isMessage_Command() {}

func (*Message_AppendPyClass) isMessage_Command() {}

func (*Message_AppendUnikernel) isMessage_Command() {}

func (*Message_AppendArg) isMessage_Command() {}

func (*Message_AppendClassMethodArg) isMessage_Command() {}

func (*Message_Invoke) isMessage_Command() {}

func (*Message_ReturnResult) isMessage_Command() {}

func (*Message_RegisterRequest) isMessage_Command() {}

func (*Message_DAG) isMessage_Command() {}

func (*Message_MarkDAGNodeDone) isMessage_Command() {}

func (*Message_RequestObject) isMessage_Command() {}

func (*Message_ResponseObject) isMessage_Command() {}

type AppendPyClass_ClassMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Params        []string               `protobuf:"bytes,2,rep,name=Params,proto3" json:"Params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPyClass_ClassMethod) Reset() {
	*x = AppendPyClass_ClassMethod{}
	mi := &file_controller_controller_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPyClass_ClassMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPyClass_ClassMethod) ProtoMessage() {}

func (x *AppendPyClass_ClassMethod) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPyClass_ClassMethod.ProtoReflect.Descriptor instead.
func (*AppendPyClass_ClassMethod) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{6, 0}
}

func (x *AppendPyClass_ClassMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppendPyClass_ClassMethod) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_controller_controller_proto protoreflect.FileDescriptor

const file_controller_controller_proto_rawDesc = "" +
	"\n" +
	"\x1bcontroller/controller.proto\x12\n" +
	"controller\x1a\x0eplatform.proto\"\x1b\n" +
	"\x03Ack\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\"\a\n" +
	"\x05Ready\"\xe5\x01\n" +
	"\x04Data\x12/\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x1b.controller.Data.ObjectTypeR\x04Type\x12\x1f\n" +
	"\x03Ref\x18\x02 \x01(\v2\v.proto.FlowH\x00R\x03Ref\x120\n" +
	"\aEncoded\x18\x03 \x01(\v2\x14.proto.EncodedObjectH\x00R\aEncoded\"O\n" +
	"\n" +
	"ObjectType\x12\x13\n" +
	"\x0fOBJ_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aOBJ_REF\x10\x01\x12\x0f\n" +
	"\vOBJ_ENCODED\x10\x02\x12\x0e\n" +
	"\n" +
	"OBJ_STREAM\x10\x03B\b\n" +
	"\x06Object\"X\n" +
	"\n" +
	"AppendData\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12,\n" +
	"\x06Object\x18\x02 \x01(\v2\x14.proto.EncodedObjectR\x06Object\"G\n" +
	"\tResources\x12\x10\n" +
	"\x03CPU\x18\x01 \x01(\x03R\x03CPU\x12\x16\n" +
	"\x06Memory\x18\x02 \x01(\x03R\x06Memory\x12\x10\n" +
	"\x03GPU\x18\x03 \x01(\x03R\x03GPU\"\x96\x02\n" +
	"\fAppendPyFunc\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Params\x18\x02 \x03(\tR\x06Params\x12\x12\n" +
	"\x04Venv\x18\x03 \x01(\tR\x04Venv\x12\"\n" +
	"\fRequirements\x18\x04 \x03(\tR\fRequirements\x12$\n" +
	"\rPickledObject\x18\x05 \x01(\fR\rPickledObject\x12+\n" +
	"\bLanguage\x18\x06 \x01(\x0e2\x0f.proto.LanguageR\bLanguage\x123\n" +
	"\tResources\x18\a \x01(\v2\x15.controller.ResourcesR\tResources\x12\x1a\n" +
	"\bReplicas\x18\b \x01(\x05R\bReplicas\"\xfb\x02\n" +
	"\rAppendPyClass\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12?\n" +
	"\aMethods\x18\x02 \x03(\v2%.controller.AppendPyClass.ClassMethodR\aMethods\x12\x12\n" +
	"\x04Venv\x18\x03 \x01(\tR\x04Venv\x12\"\n" +
	"\fRequirements\x18\x04 \x03(\tR\fRequirements\x12$\n" +
	"\rPickledObject\x18\x05 \x01(\fR\rPickledObject\x12+\n" +
	"\bLanguage\x18\x06 \x01(\x0e2\x0f.proto.LanguageR\bLanguage\x123\n" +
	"\tResources\x18\a \x01(\v2\x15.controller.ResourcesR\tResources\x12\x1a\n" +
	"\bReplicas\x18\b \x01(\x05R\bReplicas\x1a9\n" +
	"\vClassMethod\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Params\x18\x02 \x03(\tR\x06Params\"\xc8\x01\n" +
	"\bAppendGo\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Params\x18\x02 \x03(\tR\x06Params\x12\x12\n" +
	"\x04Code\x18\x03 \x01(\tR\x04Code\x12+\n" +
	"\bLanguage\x18\x04 \x01(\x0e2\x0f.proto.LanguageR\bLanguage\x123\n" +
	"\tResources\x18\x05 \x01(\v2\x15.controller.ResourcesR\tResources\x12\x1a\n" +
	"\bReplicas\x18\x06 \x01(\x05R\bReplicas\"\xd9\x01\n" +
	"\x0fAppendUnikernel\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Params\x18\x02 \x03(\tR\x06Params\x12\x1c\n" +
	"\tUnikernel\x18\x03 \x01(\tR\tUnikernel\x12+\n" +
	"\bLanguage\x18\x04 \x01(\x0e2\x0f.proto.LanguageR\bLanguage\x123\n" +
	"\tResources\x18\x05 \x01(\v2\x15.controller.ResourcesR\tResources\x12\x1a\n" +
	"\bReplicas\x18\x06 \x01(\x05R\bReplicas\"\x9b\x01\n" +
	"\tAppendArg\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\x1e\n" +
	"\n" +
	"InstanceID\x18\x02 \x01(\tR\n" +
	"InstanceID\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Param\x18\x04 \x01(\tR\x05Param\x12&\n" +
	"\x05Value\x18\x05 \x01(\v2\x10.controller.DataR\x05Value\"\xb2\x01\n" +
	"\x14AppendClassMethodArg\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\x1e\n" +
	"\n" +
	"InstanceID\x18\x02 \x01(\tR\n" +
	"InstanceID\x12\x1e\n" +
	"\n" +
	"MethodName\x18\x03 \x01(\tR\n" +
	"MethodName\x12\x14\n" +
	"\x05Param\x18\x04 \x01(\tR\x05Param\x12&\n" +
	"\x05Value\x18\x05 \x01(\v2\x10.controller.DataR\x05Value\"Z\n" +
	"\x06Invoke\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\x1e\n" +
	"\n" +
	"InstanceID\x18\x02 \x01(\tR\n" +
	"InstanceID\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\"\xac\x01\n" +
	"\fReturnResult\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\x1e\n" +
	"\n" +
	"InstanceID\x18\x02 \x01(\tR\n" +
	"InstanceID\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12(\n" +
	"\x05Value\x18\x04 \x01(\v2\x10.controller.DataH\x00R\x05Value\x12\x16\n" +
	"\x05Error\x18\x05 \x01(\tH\x00R\x05ErrorB\b\n" +
	"\x06Result\"7\n" +
	"\x0fRegisterRequest\x12$\n" +
	"\rApplicationID\x18\x01 \x01(\tR\rApplicationID\"\xcb\x02\n" +
	"\vControlNode\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Done\x18\x02 \x01(\bR\x04Done\x12\"\n" +
	"\fFunctionName\x18\x03 \x01(\tR\fFunctionName\x12;\n" +
	"\x06Params\x18\x04 \x03(\v2#.controller.ControlNode.ParamsEntryR\x06Params\x12\x18\n" +
	"\aCurrent\x18\x05 \x01(\x05R\aCurrent\x12\x1a\n" +
	"\bDataNode\x18\x06 \x01(\tR\bDataNode\x12\"\n" +
	"\fPreDataNodes\x18\a \x03(\tR\fPreDataNodes\x12\"\n" +
	"\fFunctionType\x18\b \x01(\tR\fFunctionType\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x02\n" +
	"\bDataNode\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Done\x18\x02 \x01(\bR\x04Done\x12\x16\n" +
	"\x06Lambda\x18\x03 \x01(\tR\x06Lambda\x12\x14\n" +
	"\x05Ready\x18\x04 \x01(\bR\x05Ready\x12(\n" +
	"\x0fSufControlNodes\x18\x05 \x03(\tR\x0fSufControlNodes\x12+\n" +
	"\x0ePreControlNode\x18\x06 \x01(\tH\x00R\x0ePreControlNode\x88\x01\x01\x12#\n" +
	"\n" +
	"ParentNode\x18\a \x01(\tH\x01R\n" +
	"ParentNode\x88\x01\x01\x12\x1c\n" +
	"\tChildNode\x18\b \x03(\tR\tChildNodeB\x11\n" +
	"\x0f_PreControlNodeB\r\n" +
	"\v_ParentNode\"\x96\x01\n" +
	"\aDAGNode\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12;\n" +
	"\vControlNode\x18\x02 \x01(\v2\x17.controller.ControlNodeH\x00R\vControlNode\x122\n" +
	"\bDataNode\x18\x03 \x01(\v2\x14.controller.DataNodeH\x00R\bDataNodeB\x06\n" +
	"\x04Node\"0\n" +
	"\x03DAG\x12)\n" +
	"\x05Nodes\x18\x01 \x03(\v2\x13.controller.DAGNodeR\x05Nodes\"G\n" +
	"\x0fMarkDAGNodeDone\x12\x16\n" +
	"\x06NodeId\x18\x01 \x01(\tR\x06NodeId\x12\x1c\n" +
	"\tSessionId\x18\x02 \x01(\tR\tSessionId\"7\n" +
	"\rRequestObject\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Target\x18\x02 \x01(\tR\x06Target\"b\n" +
	"\x0eResponseObject\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12*\n" +
	"\x05Value\x18\x02 \x01(\v2\x14.proto.EncodedObjectR\x05Value\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error\"\x88\b\n" +
	"\aMessage\x12+\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x17.controller.CommandTypeR\x04Type\x12#\n" +
	"\x03Ack\x18\x02 \x01(\v2\x0f.controller.AckH\x00R\x03Ack\x12)\n" +
	"\x05Ready\x18\x03 \x01(\v2\x11.controller.ReadyH\x00R\x05Ready\x128\n" +
	"\n" +
	"AppendData\x18\x04 \x01(\v2\x16.controller.AppendDataH\x00R\n" +
	"AppendData\x122\n" +
	"\bAppendGo\x18\x05 \x01(\v2\x14.controller.AppendGoH\x00R\bAppendGo\x12>\n" +
	"\fAppendPyFunc\x18\x06 \x01(\v2\x18.controller.AppendPyFuncH\x00R\fAppendPyFunc\x12A\n" +
	"\rAppendPyClass\x18\a \x01(\v2\x19.controller.AppendPyClassH\x00R\rAppendPyClass\x12G\n" +
	"\x0fAppendUnikernel\x18\b \x01(\v2\x1b.controller.AppendUnikernelH\x00R\x0fAppendUnikernel\x125\n" +
	"\tAppendArg\x18\t \x01(\v2\x15.controller.AppendArgH\x00R\tAppendArg\x12V\n" +
	"\x14AppendClassMethodArg\x18\n" +
	" \x01(\v2 .controller.AppendClassMethodArgH\x00R\x14AppendClassMethodArg\x12,\n" +
	"\x06Invoke\x18\v \x01(\v2\x12.controller.InvokeH\x00R\x06Invoke\x12>\n" +
	"\fReturnResult\x18\f \x01(\v2\x18.controller.ReturnResultH\x00R\fReturnResult\x12G\n" +
	"\x0fRegisterRequest\x18\r \x01(\v2\x1b.controller.RegisterRequestH\x00R\x0fRegisterRequest\x12#\n" +
	"\x03DAG\x18\x0e \x01(\v2\x0f.controller.DAGH\x00R\x03DAG\x12G\n" +
	"\x0fMarkDAGNodeDone\x18\x0f \x01(\v2\x1b.controller.MarkDAGNodeDoneH\x00R\x0fMarkDAGNodeDone\x12A\n" +
	"\rRequestObject\x18\x10 \x01(\v2\x19.controller.RequestObjectH\x00R\rRequestObject\x12D\n" +
	"\x0eResponseObject\x18\x11 \x01(\v2\x1a.controller.ResponseObjectH\x00R\x0eResponseObjectB\t\n" +
	"\aCommand*\xea\x02\n" +
	"\vCommandType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ACK\x10\x01\x12\f\n" +
	"\bFR_READY\x10\x02\x12\x12\n" +
	"\x0eFR_APPEND_DATA\x10\x03\x12\x10\n" +
	"\fFR_APPEND_GO\x10\x04\x12\x15\n" +
	"\x11FR_APPEND_PY_FUNC\x10\x05\x12\x16\n" +
	"\x12FR_APPEND_PY_CLASS\x10\x06\x12\x17\n" +
	"\x13FR_APPEND_UNIKERNEL\x10\a\x12\x11\n" +
	"\rFR_APPEND_ARG\x10\b\x12\x1e\n" +
	"\x1aFR_APPEND_CLASS_METHOD_ARG\x10\t\x12\r\n" +
	"\tFR_INVOKE\x10\n" +
	"\x12\x14\n" +
	"\x10BK_RETURN_RESULT\x10\v\x12\x17\n" +
	"\x13FR_REGISTER_REQUEST\x10\f\x12\n" +
	"\n" +
	"\x06FR_DAG\x10\r\x12\x19\n" +
	"\x15FR_MARK_DAG_NODE_DONE\x10\x0e\x12\x15\n" +
	"\x11FR_REQUEST_OBJECT\x10\x0f\x12\x16\n" +
	"\x12BK_RESPONSE_OBJECT\x10\x102D\n" +
	"\aService\x129\n" +
	"\aSession\x12\x13.controller.Message\x1a\x13.controller.Message\"\x00(\x010\x01B+Z)github.com/9triver/ignis/proto/controllerb\x06proto3"

var (
	file_controller_controller_proto_rawDescOnce sync.Once
	file_controller_controller_proto_rawDescData []byte
)

func file_controller_controller_proto_rawDescGZIP() []byte {
	file_controller_controller_proto_rawDescOnce.Do(func() {
		file_controller_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_controller_proto_rawDesc), len(file_controller_controller_proto_rawDesc)))
	})
	return file_controller_controller_proto_rawDescData
}

var file_controller_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_controller_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_controller_controller_proto_goTypes = []any{
	(CommandType)(0),                  // 0: controller.CommandType
	(Data_ObjectType)(0),              // 1: controller.Data.ObjectType
	(*Ack)(nil),                       // 2: controller.Ack
	(*Ready)(nil),                     // 3: controller.Ready
	(*Data)(nil),                      // 4: controller.Data
	(*AppendData)(nil),                // 5: controller.AppendData
	(*Resources)(nil),                 // 6: controller.Resources
	(*AppendPyFunc)(nil),              // 7: controller.AppendPyFunc
	(*AppendPyClass)(nil),             // 8: controller.AppendPyClass
	(*AppendGo)(nil),                  // 9: controller.AppendGo
	(*AppendUnikernel)(nil),           // 10: controller.AppendUnikernel
	(*AppendArg)(nil),                 // 11: controller.AppendArg
	(*AppendClassMethodArg)(nil),      // 12: controller.AppendClassMethodArg
	(*Invoke)(nil),                    // 13: controller.Invoke
	(*ReturnResult)(nil),              // 14: controller.ReturnResult
	(*RegisterRequest)(nil),           // 15: controller.RegisterRequest
	(*ControlNode)(nil),               // 16: controller.ControlNode
	(*DataNode)(nil),                  // 17: controller.DataNode
	(*DAGNode)(nil),                   // 18: controller.DAGNode
	(*DAG)(nil),                       // 19: controller.DAG
	(*MarkDAGNodeDone)(nil),           // 20: controller.MarkDAGNodeDone
	(*RequestObject)(nil),             // 21: controller.RequestObject
	(*ResponseObject)(nil),            // 22: controller.ResponseObject
	(*Message)(nil),                   // 23: controller.Message
	(*AppendPyClass_ClassMethod)(nil), // 24: controller.AppendPyClass.ClassMethod
	nil,                               // 25: controller.ControlNode.ParamsEntry
	(*proto.Flow)(nil),                // 26: proto.Flow
	(*proto.EncodedObject)(nil),       // 27: proto.EncodedObject
	(proto.Language)(0),               // 28: proto.Language
}
var file_controller_controller_proto_depIdxs = []int32{
	1,  // 0: controller.Data.Type:type_name -> controller.Data.ObjectType
	26, // 1: controller.Data.Ref:type_name -> proto.Flow
	27, // 2: controller.Data.Encoded:type_name -> proto.EncodedObject
	27, // 3: controller.AppendData.Object:type_name -> proto.EncodedObject
	28, // 4: controller.AppendPyFunc.Language:type_name -> proto.Language
	6,  // 5: controller.AppendPyFunc.Resources:type_name -> controller.Resources
	24, // 6: controller.AppendPyClass.Methods:type_name -> controller.AppendPyClass.ClassMethod
	28, // 7: controller.AppendPyClass.Language:type_name -> proto.Language
	6,  // 8: controller.AppendPyClass.Resources:type_name -> controller.Resources
	28, // 9: controller.AppendGo.Language:type_name -> proto.Language
	6,  // 10: controller.AppendGo.Resources:type_name -> controller.Resources
	28, // 11: controller.AppendUnikernel.Language:type_name -> proto.Language
	6,  // 12: controller.AppendUnikernel.Resources:type_name -> controller.Resources
	4,  // 13: controller.AppendArg.Value:type_name -> controller.Data
	4,  // 14: controller.AppendClassMethodArg.Value:type_name -> controller.Data
	4,  // 15: controller.ReturnResult.Value:type_name -> controller.Data
	25, // 16: controller.ControlNode.Params:type_name -> controller.ControlNode.ParamsEntry
	16, // 17: controller.DAGNode.ControlNode:type_name -> controller.ControlNode
	17, // 18: controller.DAGNode.DataNode:type_name -> controller.DataNode
	18, // 19: controller.DAG.Nodes:type_name -> controller.DAGNode
	27, // 20: controller.ResponseObject.Value:type_name -> proto.EncodedObject
	0,  // 21: controller.Message.Type:type_name -> controller.CommandType
	2,  // 22: controller.Message.Ack:type_name -> controller.Ack
	3,  // 23: controller.Message.Ready:type_name -> controller.Ready
	5,  // 24: controller.Message.AppendData:type_name -> controller.AppendData
	9,  // 25: controller.Message.AppendGo:type_name -> controller.AppendGo
	7,  // 26: controller.Message.AppendPyFunc:type_name -> controller.AppendPyFunc
	8,  // 27: controller.Message.AppendPyClass:type_name -> controller.AppendPyClass
	10, // 28: controller.Message.AppendUnikernel:type_name -> controller.AppendUnikernel
	11, // 29: controller.Message.AppendArg:type_name -> controller.AppendArg
	12, // 30: controller.Message.AppendClassMethodArg:type_name -> controller.AppendClassMethodArg
	13, // 31: controller.Message.Invoke:type_name -> controller.Invoke
	14, // 32: controller.Message.ReturnResult:type_name -> controller.ReturnResult
	15, // 33: controller.Message.RegisterRequest:type_name -> controller.RegisterRequest
	19, // 34: controller.Message.DAG:type_name -> controller.DAG
	20, // 35: controller.Message.MarkDAGNodeDone:type_name -> controller.MarkDAGNodeDone
	21, // 36: controller.Message.RequestObject:type_name -> controller.RequestObject
	22, // 37: controller.Message.ResponseObject:type_name -> controller.ResponseObject
	23, // 38: controller.Service.Session:input_type -> controller.Message
	23, // 39: controller.Service.Session:output_type -> controller.Message
	39, // [39:40] is the sub-list for method output_type
	38, // [38:39] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_controller_controller_proto_init() }
func file_controller_controller_proto_init() {
	if File_controller_controller_proto != nil {
		return
	}
	file_controller_controller_proto_msgTypes[2].OneofWrappers = []any{
		(*Data_Ref)(nil),
		(*Data_Encoded)(nil),
	}
	file_controller_controller_proto_msgTypes[12].OneofWrappers = []any{
		(*ReturnResult_Value)(nil),
		(*ReturnResult_Error)(nil),
	}
	file_controller_controller_proto_msgTypes[15].OneofWrappers = []any{}
	file_controller_controller_proto_msgTypes[16].OneofWrappers = []any{
		(*DAGNode_ControlNode)(nil),
		(*DAGNode_DataNode)(nil),
	}
	file_controller_controller_proto_msgTypes[21].OneofWrappers = []any{
		(*Message_Ack)(nil),
		(*Message_Ready)(nil),
		(*Message_AppendData)(nil),
		(*Message_AppendGo)(nil),
		(*Message_AppendPyFunc)(nil),
		(*Message_AppendPyClass)(nil),
		(*Message_AppendUnikernel)(nil),
		(*Message_AppendArg)(nil),
		(*Message_AppendClassMethodArg)(nil),
		(*Message_Invoke)(nil),
		(*Message_ReturnResult)(nil),
		(*Message_RegisterRequest)(nil),
		(*Message_DAG)(nil),
		(*Message_MarkDAGNodeDone)(nil),
		(*Message_RequestObject)(nil),
		(*Message_ResponseObject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_controller_proto_rawDesc), len(file_controller_controller_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_controller_proto_goTypes,
		DependencyIndexes: file_controller_controller_proto_depIdxs,
		EnumInfos:         file_controller_controller_proto_enumTypes,
		MessageInfos:      file_controller_controller_proto_msgTypes,
	}.Build()
	File_controller_controller_proto = out.File
	file_controller_controller_proto_goTypes = nil
	file_controller_controller_proto_depIdxs = nil
}
