// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: common/logger.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 日志级别，对应 logrus 的日志级别
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNKNOWN LogLevel = 0
	LogLevel_LOG_LEVEL_TRACE   LogLevel = 1 // Trace level
	LogLevel_LOG_LEVEL_DEBUG   LogLevel = 2 // Debug level
	LogLevel_LOG_LEVEL_INFO    LogLevel = 3 // Info level
	LogLevel_LOG_LEVEL_WARN    LogLevel = 4 // Warn level
	LogLevel_LOG_LEVEL_ERROR   LogLevel = 5 // Error level
	LogLevel_LOG_LEVEL_FATAL   LogLevel = 6 // Fatal level
	LogLevel_LOG_LEVEL_PANIC   LogLevel = 7 // Panic level
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNKNOWN",
		1: "LOG_LEVEL_TRACE",
		2: "LOG_LEVEL_DEBUG",
		3: "LOG_LEVEL_INFO",
		4: "LOG_LEVEL_WARN",
		5: "LOG_LEVEL_ERROR",
		6: "LOG_LEVEL_FATAL",
		7: "LOG_LEVEL_PANIC",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNKNOWN": 0,
		"LOG_LEVEL_TRACE":   1,
		"LOG_LEVEL_DEBUG":   2,
		"LOG_LEVEL_INFO":    3,
		"LOG_LEVEL_WARN":    4,
		"LOG_LEVEL_ERROR":   5,
		"LOG_LEVEL_FATAL":   6,
		"LOG_LEVEL_PANIC":   7,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_logger_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_common_logger_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_common_logger_proto_rawDescGZIP(), []int{0}
}

type StreamControl_ControlType int32

const (
	StreamControl_CONTROL_UNKNOWN   StreamControl_ControlType = 0
	StreamControl_CONTROL_HEARTBEAT StreamControl_ControlType = 1 // 心跳
	StreamControl_CONTROL_FLUSH     StreamControl_ControlType = 2 // 刷新缓冲区
	StreamControl_CONTROL_CLOSE     StreamControl_ControlType = 3 // 关闭流
)

// Enum value maps for StreamControl_ControlType.
var (
	StreamControl_ControlType_name = map[int32]string{
		0: "CONTROL_UNKNOWN",
		1: "CONTROL_HEARTBEAT",
		2: "CONTROL_FLUSH",
		3: "CONTROL_CLOSE",
	}
	StreamControl_ControlType_value = map[string]int32{
		"CONTROL_UNKNOWN":   0,
		"CONTROL_HEARTBEAT": 1,
		"CONTROL_FLUSH":     2,
		"CONTROL_CLOSE":     3,
	}
)

func (x StreamControl_ControlType) Enum() *StreamControl_ControlType {
	p := new(StreamControl_ControlType)
	*p = x
	return p
}

func (x StreamControl_ControlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamControl_ControlType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_logger_proto_enumTypes[1].Descriptor()
}

func (StreamControl_ControlType) Type() protoreflect.EnumType {
	return &file_common_logger_proto_enumTypes[1]
}

func (x StreamControl_ControlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamControl_ControlType.Descriptor instead.
func (StreamControl_ControlType) EnumDescriptor() ([]byte, []int) {
	return file_common_logger_proto_rawDescGZIP(), []int{3, 0}
}

// 日志字段，用于存储 logrus Fields
type LogField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // JSON 编码的值，支持各种类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogField) Reset() {
	*x = LogField{}
	mi := &file_common_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogField) ProtoMessage() {}

func (x *LogField) ProtoReflect() protoreflect.Message {
	mi := &file_common_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogField.ProtoReflect.Descriptor instead.
func (*LogField) Descriptor() ([]byte, []int) {
	return file_common_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LogField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 调用栈信息
type CallerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`         // 文件名
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`        // 行号
	Function      string                 `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"` // 函数名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallerInfo) Reset() {
	*x = CallerInfo{}
	mi := &file_common_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallerInfo) ProtoMessage() {}

func (x *CallerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallerInfo.ProtoReflect.Descriptor instead.
func (*CallerInfo) Descriptor() ([]byte, []int) {
	return file_common_logger_proto_rawDescGZIP(), []int{1}
}

func (x *CallerInfo) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *CallerInfo) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *CallerInfo) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

// 单条日志条目
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础信息
	Timestamp int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // Unix 时间戳（纳秒）
	Level     LogLevel `protobuf:"varint,2,opt,name=level,proto3,enum=common.LogLevel" json:"level,omitempty"` // 日志级别
	Message   string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                   // 日志消息
	// 元数据
	Fields        []*LogField `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"` // logrus Fields（键值对）
	Caller        *CallerInfo `protobuf:"bytes,5,opt,name=caller,proto3" json:"caller,omitempty"` // 调用栈信息（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_common_logger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_logger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_common_logger_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNKNOWN
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() []*LogField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LogEntry) GetCaller() *CallerInfo {
	if x != nil {
		return x.Caller
	}
	return nil
}

// 流式控制消息
type StreamControl struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          StreamControl_ControlType `protobuf:"varint,1,opt,name=type,proto3,enum=common.StreamControl_ControlType" json:"type,omitempty"`
	Metadata      map[string]string         `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外的元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamControl) Reset() {
	*x = StreamControl{}
	mi := &file_common_logger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControl) ProtoMessage() {}

func (x *StreamControl) ProtoReflect() protoreflect.Message {
	mi := &file_common_logger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControl.ProtoReflect.Descriptor instead.
func (*StreamControl) Descriptor() ([]byte, []int) {
	return file_common_logger_proto_rawDescGZIP(), []int{3}
}

func (x *StreamControl) GetType() StreamControl_ControlType {
	if x != nil {
		return x.Type
	}
	return StreamControl_CONTROL_UNKNOWN
}

func (x *StreamControl) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_common_logger_proto protoreflect.FileDescriptor

const file_common_logger_proto_rawDesc = "" +
	"\n" +
	"\x13common/logger.proto\x12\x06common\"2\n" +
	"\bLogField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"P\n" +
	"\n" +
	"CallerInfo\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x1a\n" +
	"\bfunction\x18\x03 \x01(\tR\bfunction\"\xc0\x01\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12&\n" +
	"\x05level\x18\x02 \x01(\x0e2\x10.common.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12(\n" +
	"\x06fields\x18\x04 \x03(\v2\x10.common.LogFieldR\x06fields\x12*\n" +
	"\x06caller\x18\x05 \x01(\v2\x12.common.CallerInfoR\x06caller\"\xa5\x02\n" +
	"\rStreamControl\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.common.StreamControl.ControlTypeR\x04type\x12?\n" +
	"\bmetadata\x18\x02 \x03(\v2#.common.StreamControl.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\vControlType\x12\x13\n" +
	"\x0fCONTROL_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11CONTROL_HEARTBEAT\x10\x01\x12\x11\n" +
	"\rCONTROL_FLUSH\x10\x02\x12\x11\n" +
	"\rCONTROL_CLOSE\x10\x03*\xb2\x01\n" +
	"\bLogLevel\x12\x15\n" +
	"\x11LOG_LEVEL_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_TRACE\x10\x01\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x03\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x04\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x05\x12\x13\n" +
	"\x0fLOG_LEVEL_FATAL\x10\x06\x12\x13\n" +
	"\x0fLOG_LEVEL_PANIC\x10\aB1Z/github.com/9triver/ignis/proto/commonb\x06proto3"

var (
	file_common_logger_proto_rawDescOnce sync.Once
	file_common_logger_proto_rawDescData []byte
)

func file_common_logger_proto_rawDescGZIP() []byte {
	file_common_logger_proto_rawDescOnce.Do(func() {
		file_common_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_logger_proto_rawDesc), len(file_common_logger_proto_rawDesc)))
	})
	return file_common_logger_proto_rawDescData
}

var file_common_logger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_logger_proto_goTypes = []any{
	(LogLevel)(0),                  // 0: common.LogLevel
	(StreamControl_ControlType)(0), // 1: common.StreamControl.ControlType
	(*LogField)(nil),               // 2: common.LogField
	(*CallerInfo)(nil),             // 3: common.CallerInfo
	(*LogEntry)(nil),               // 4: common.LogEntry
	(*StreamControl)(nil),          // 5: common.StreamControl
	nil,                            // 6: common.StreamControl.MetadataEntry
}
var file_common_logger_proto_depIdxs = []int32{
	0, // 0: common.LogEntry.level:type_name -> common.LogLevel
	2, // 1: common.LogEntry.fields:type_name -> common.LogField
	3, // 2: common.LogEntry.caller:type_name -> common.CallerInfo
	1, // 3: common.StreamControl.type:type_name -> common.StreamControl.ControlType
	6, // 4: common.StreamControl.metadata:type_name -> common.StreamControl.MetadataEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_logger_proto_init() }
func file_common_logger_proto_init() {
	if File_common_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_logger_proto_rawDesc), len(file_common_logger_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_logger_proto_goTypes,
		DependencyIndexes: file_common_logger_proto_depIdxs,
		EnumInfos:         file_common_logger_proto_enumTypes,
		MessageInfos:      file_common_logger_proto_msgTypes,
	}.Build()
	File_common_logger_proto = out.File
	file_common_logger_proto_goTypes = nil
	file_common_logger_proto_depIdxs = nil
}
