// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: common/types.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Language of supported object
type Language int32

const (
	Language_LANG_UNKNOWN Language = 0
	Language_LANG_JSON    Language = 1 // Values that can be represented as JSON string, can be encoded/decoded
	Language_LANG_GO      Language = 2 // Values that are only compatible with Go actors.
	Language_LANG_PYTHON  Language = 3 // Values that are only compatible with Python actors.
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "LANG_UNKNOWN",
		1: "LANG_JSON",
		2: "LANG_GO",
		3: "LANG_PYTHON",
	}
	Language_value = map[string]int32{
		"LANG_UNKNOWN": 0,
		"LANG_JSON":    1,
		"LANG_GO":      2,
		"LANG_PYTHON":  3,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_common_types_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

// ObjectRef is a reference to an object in the store
type ObjectRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`         // Object ID
	Source        string                 `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"` // Source store ID (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	mi := &file_common_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectRef) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ObjectRef) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// EncodedObject stores a byte encoded object
// This is a unified version used across the system
type EncodedObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`                                   // if returned from ipc call, id won't be set
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`                               // serialized object data, or nil if current object is a stream
	Source        string                 `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`                           // source store ID (optional, for store service)
	Language      Language               `protobuf:"varint,4,opt,name=Language,proto3,enum=common.Language" json:"Language,omitempty"` // if is JSON, it can be decoded to either Go, Python, or else it can only be decoded to corresponding language.
	IsStream      bool                   `protobuf:"varint,5,opt,name=IsStream,proto3" json:"IsStream,omitempty"`                      // mark if the object is a stream (unified field name)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodedObject) Reset() {
	*x = EncodedObject{}
	mi := &file_common_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedObject) ProtoMessage() {}

func (x *EncodedObject) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedObject.ProtoReflect.Descriptor instead.
func (*EncodedObject) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{1}
}

func (x *EncodedObject) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *EncodedObject) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EncodedObject) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EncodedObject) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANG_UNKNOWN
}

func (x *EncodedObject) GetIsStream() bool {
	if x != nil {
		return x.IsStream
	}
	return false
}

type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectID      string                 `protobuf:"bytes,1,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	EoS           bool                   `protobuf:"varint,3,opt,name=EoS,proto3" json:"EoS,omitempty"`
	Value         *EncodedObject         `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_common_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{2}
}

func (x *StreamChunk) GetObjectID() string {
	if x != nil {
		return x.ObjectID
	}
	return ""
}

func (x *StreamChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StreamChunk) GetEoS() bool {
	if x != nil {
		return x.EoS
	}
	return false
}

func (x *StreamChunk) GetValue() *EncodedObject {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StreamChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_common_types_proto protoreflect.FileDescriptor

const file_common_types_proto_rawDesc = "" +
	"\n" +
	"\x12common/types.proto\x12\x06common\"3\n" +
	"\tObjectRef\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Source\x18\x02 \x01(\tR\x06Source\"\x95\x01\n" +
	"\rEncodedObject\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\x12\x16\n" +
	"\x06Source\x18\x03 \x01(\tR\x06Source\x12,\n" +
	"\bLanguage\x18\x04 \x01(\x0e2\x10.common.LanguageR\bLanguage\x12\x1a\n" +
	"\bIsStream\x18\x05 \x01(\bR\bIsStream\"\x96\x01\n" +
	"\vStreamChunk\x12\x1a\n" +
	"\bObjectID\x18\x01 \x01(\tR\bObjectID\x12\x16\n" +
	"\x06Offset\x18\x02 \x01(\x03R\x06Offset\x12\x10\n" +
	"\x03EoS\x18\x03 \x01(\bR\x03EoS\x12+\n" +
	"\x05Value\x18\x04 \x01(\v2\x15.common.EncodedObjectR\x05Value\x12\x14\n" +
	"\x05Error\x18\x05 \x01(\tR\x05Error*I\n" +
	"\bLanguage\x12\x10\n" +
	"\fLANG_UNKNOWN\x10\x00\x12\r\n" +
	"\tLANG_JSON\x10\x01\x12\v\n" +
	"\aLANG_GO\x10\x02\x12\x0f\n" +
	"\vLANG_PYTHON\x10\x03B1Z/github.com/9triver/ignis/proto/commonb\x06proto3"

var (
	file_common_types_proto_rawDescOnce sync.Once
	file_common_types_proto_rawDescData []byte
)

func file_common_types_proto_rawDescGZIP() []byte {
	file_common_types_proto_rawDescOnce.Do(func() {
		file_common_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)))
	})
	return file_common_types_proto_rawDescData
}

var file_common_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_types_proto_goTypes = []any{
	(Language)(0),         // 0: common.Language
	(*ObjectRef)(nil),     // 1: common.ObjectRef
	(*EncodedObject)(nil), // 2: common.EncodedObject
	(*StreamChunk)(nil),   // 3: common.StreamChunk
}
var file_common_types_proto_depIdxs = []int32{
	0, // 0: common.EncodedObject.Language:type_name -> common.Language
	2, // 1: common.StreamChunk.Value:type_name -> common.EncodedObject
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_types_proto_init() }
func file_common_types_proto_init() {
	if File_common_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_proto_goTypes,
		DependencyIndexes: file_common_types_proto_depIdxs,
		EnumInfos:         file_common_types_proto_enumTypes,
		MessageInfos:      file_common_types_proto_msgTypes,
	}.Build()
	File_common_types_proto = out.File
	file_common_types_proto_goTypes = nil
	file_common_types_proto_depIdxs = nil
}
