// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: resource/store/store.proto

package store

import (
	common "github.com/9triver/ignis/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *common.EncodedObject  `protobuf:"bytes,1,opt,name=Object,proto3" json:"Object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveObjectRequest) Reset() {
	*x = SaveObjectRequest{}
	mi := &file_resource_store_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveObjectRequest) ProtoMessage() {}

func (x *SaveObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_store_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveObjectRequest.ProtoReflect.Descriptor instead.
func (*SaveObjectRequest) Descriptor() ([]byte, []int) {
	return file_resource_store_store_proto_rawDescGZIP(), []int{0}
}

func (x *SaveObjectRequest) GetObject() *common.EncodedObject {
	if x != nil {
		return x.Object
	}
	return nil
}

type SaveObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectRef     *common.ObjectRef      `protobuf:"bytes,1,opt,name=ObjectRef,proto3" json:"ObjectRef,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveObjectResponse) Reset() {
	*x = SaveObjectResponse{}
	mi := &file_resource_store_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveObjectResponse) ProtoMessage() {}

func (x *SaveObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_store_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveObjectResponse.ProtoReflect.Descriptor instead.
func (*SaveObjectResponse) Descriptor() ([]byte, []int) {
	return file_resource_store_store_proto_rawDescGZIP(), []int{1}
}

func (x *SaveObjectResponse) GetObjectRef() *common.ObjectRef {
	if x != nil {
		return x.ObjectRef
	}
	return nil
}

func (x *SaveObjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveObjectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectRef     *common.ObjectRef      `protobuf:"bytes,1,opt,name=ObjectRef,proto3" json:"ObjectRef,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_resource_store_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_store_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_resource_store_store_proto_rawDescGZIP(), []int{2}
}

func (x *GetObjectRequest) GetObjectRef() *common.ObjectRef {
	if x != nil {
		return x.ObjectRef
	}
	return nil
}

type GetObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *common.EncodedObject  `protobuf:"bytes,1,opt,name=Object,proto3" json:"Object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	mi := &file_resource_store_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_store_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_resource_store_store_proto_rawDescGZIP(), []int{3}
}

func (x *GetObjectResponse) GetObject() *common.EncodedObject {
	if x != nil {
		return x.Object
	}
	return nil
}

type GetStreamChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectID      string                 `protobuf:"bytes,1,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamChunkRequest) Reset() {
	*x = GetStreamChunkRequest{}
	mi := &file_resource_store_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamChunkRequest) ProtoMessage() {}

func (x *GetStreamChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_store_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamChunkRequest.ProtoReflect.Descriptor instead.
func (*GetStreamChunkRequest) Descriptor() ([]byte, []int) {
	return file_resource_store_store_proto_rawDescGZIP(), []int{4}
}

func (x *GetStreamChunkRequest) GetObjectID() string {
	if x != nil {
		return x.ObjectID
	}
	return ""
}

func (x *GetStreamChunkRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetStreamChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *common.StreamChunk    `protobuf:"bytes,1,opt,name=Chunk,proto3" json:"Chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamChunkResponse) Reset() {
	*x = GetStreamChunkResponse{}
	mi := &file_resource_store_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamChunkResponse) ProtoMessage() {}

func (x *GetStreamChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_store_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamChunkResponse.ProtoReflect.Descriptor instead.
func (*GetStreamChunkResponse) Descriptor() ([]byte, []int) {
	return file_resource_store_store_proto_rawDescGZIP(), []int{5}
}

func (x *GetStreamChunkResponse) GetChunk() *common.StreamChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type SaveStreamChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *common.StreamChunk    `protobuf:"bytes,1,opt,name=Chunk,proto3" json:"Chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveStreamChunkRequest) Reset() {
	*x = SaveStreamChunkRequest{}
	mi := &file_resource_store_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveStreamChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStreamChunkRequest) ProtoMessage() {}

func (x *SaveStreamChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_store_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStreamChunkRequest.ProtoReflect.Descriptor instead.
func (*SaveStreamChunkRequest) Descriptor() ([]byte, []int) {
	return file_resource_store_store_proto_rawDescGZIP(), []int{6}
}

func (x *SaveStreamChunkRequest) GetChunk() *common.StreamChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type SaveStreamChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveStreamChunkResponse) Reset() {
	*x = SaveStreamChunkResponse{}
	mi := &file_resource_store_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveStreamChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStreamChunkResponse) ProtoMessage() {}

func (x *SaveStreamChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_store_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStreamChunkResponse.ProtoReflect.Descriptor instead.
func (*SaveStreamChunkResponse) Descriptor() ([]byte, []int) {
	return file_resource_store_store_proto_rawDescGZIP(), []int{7}
}

var File_resource_store_store_proto protoreflect.FileDescriptor

const file_resource_store_store_proto_rawDesc = "" +
	"\n" +
	"\x1aresource/store/store.proto\x12\x0eresource.store\x1a\x12common/types.proto\"B\n" +
	"\x11SaveObjectRequest\x12-\n" +
	"\x06Object\x18\x01 \x01(\v2\x15.common.EncodedObjectR\x06Object\"u\n" +
	"\x12SaveObjectResponse\x12/\n" +
	"\tObjectRef\x18\x01 \x01(\v2\x11.common.ObjectRefR\tObjectRef\x12\x18\n" +
	"\aSuccess\x18\x02 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error\"C\n" +
	"\x10GetObjectRequest\x12/\n" +
	"\tObjectRef\x18\x01 \x01(\v2\x11.common.ObjectRefR\tObjectRef\"B\n" +
	"\x11GetObjectResponse\x12-\n" +
	"\x06Object\x18\x01 \x01(\v2\x15.common.EncodedObjectR\x06Object\"K\n" +
	"\x15GetStreamChunkRequest\x12\x1a\n" +
	"\bObjectID\x18\x01 \x01(\tR\bObjectID\x12\x16\n" +
	"\x06Offset\x18\x02 \x01(\x03R\x06Offset\"C\n" +
	"\x16GetStreamChunkResponse\x12)\n" +
	"\x05Chunk\x18\x01 \x01(\v2\x13.common.StreamChunkR\x05Chunk\"C\n" +
	"\x16SaveStreamChunkRequest\x12)\n" +
	"\x05Chunk\x18\x01 \x01(\v2\x13.common.StreamChunkR\x05Chunk\"\x19\n" +
	"\x17SaveStreamChunkResponse2\xf5\x02\n" +
	"\aService\x12S\n" +
	"\n" +
	"SaveObject\x12!.resource.store.SaveObjectRequest\x1a\".resource.store.SaveObjectResponse\x12b\n" +
	"\x0fSaveStreamChunk\x12&.resource.store.SaveStreamChunkRequest\x1a'.resource.store.SaveStreamChunkResponse\x12P\n" +
	"\tGetObject\x12 .resource.store.GetObjectRequest\x1a!.resource.store.GetObjectResponse\x12_\n" +
	"\x0eGetStreamChunk\x12%.resource.store.GetStreamChunkRequest\x1a&.resource.store.GetStreamChunkResponseB9Z7github.com/9triver/ignis/proto/resource/storeb\x06proto3"

var (
	file_resource_store_store_proto_rawDescOnce sync.Once
	file_resource_store_store_proto_rawDescData []byte
)

func file_resource_store_store_proto_rawDescGZIP() []byte {
	file_resource_store_store_proto_rawDescOnce.Do(func() {
		file_resource_store_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_store_store_proto_rawDesc), len(file_resource_store_store_proto_rawDesc)))
	})
	return file_resource_store_store_proto_rawDescData
}

var file_resource_store_store_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_resource_store_store_proto_goTypes = []any{
	(*SaveObjectRequest)(nil),       // 0: resource.store.SaveObjectRequest
	(*SaveObjectResponse)(nil),      // 1: resource.store.SaveObjectResponse
	(*GetObjectRequest)(nil),        // 2: resource.store.GetObjectRequest
	(*GetObjectResponse)(nil),       // 3: resource.store.GetObjectResponse
	(*GetStreamChunkRequest)(nil),   // 4: resource.store.GetStreamChunkRequest
	(*GetStreamChunkResponse)(nil),  // 5: resource.store.GetStreamChunkResponse
	(*SaveStreamChunkRequest)(nil),  // 6: resource.store.SaveStreamChunkRequest
	(*SaveStreamChunkResponse)(nil), // 7: resource.store.SaveStreamChunkResponse
	(*common.EncodedObject)(nil),    // 8: common.EncodedObject
	(*common.ObjectRef)(nil),        // 9: common.ObjectRef
	(*common.StreamChunk)(nil),      // 10: common.StreamChunk
}
var file_resource_store_store_proto_depIdxs = []int32{
	8,  // 0: resource.store.SaveObjectRequest.Object:type_name -> common.EncodedObject
	9,  // 1: resource.store.SaveObjectResponse.ObjectRef:type_name -> common.ObjectRef
	9,  // 2: resource.store.GetObjectRequest.ObjectRef:type_name -> common.ObjectRef
	8,  // 3: resource.store.GetObjectResponse.Object:type_name -> common.EncodedObject
	10, // 4: resource.store.GetStreamChunkResponse.Chunk:type_name -> common.StreamChunk
	10, // 5: resource.store.SaveStreamChunkRequest.Chunk:type_name -> common.StreamChunk
	0,  // 6: resource.store.Service.SaveObject:input_type -> resource.store.SaveObjectRequest
	6,  // 7: resource.store.Service.SaveStreamChunk:input_type -> resource.store.SaveStreamChunkRequest
	2,  // 8: resource.store.Service.GetObject:input_type -> resource.store.GetObjectRequest
	4,  // 9: resource.store.Service.GetStreamChunk:input_type -> resource.store.GetStreamChunkRequest
	1,  // 10: resource.store.Service.SaveObject:output_type -> resource.store.SaveObjectResponse
	7,  // 11: resource.store.Service.SaveStreamChunk:output_type -> resource.store.SaveStreamChunkResponse
	3,  // 12: resource.store.Service.GetObject:output_type -> resource.store.GetObjectResponse
	5,  // 13: resource.store.Service.GetStreamChunk:output_type -> resource.store.GetStreamChunkResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_resource_store_store_proto_init() }
func file_resource_store_store_proto_init() {
	if File_resource_store_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_store_store_proto_rawDesc), len(file_resource_store_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_store_store_proto_goTypes,
		DependencyIndexes: file_resource_store_store_proto_depIdxs,
		MessageInfos:      file_resource_store_store_proto_msgTypes,
	}.Build()
	File_resource_store_store_proto = out.File
	file_resource_store_store_proto_goTypes = nil
	file_resource_store_store_proto_depIdxs = nil
}
