// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: resource/store/store.proto

package store

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_SaveObject_FullMethodName      = "/resource.store.Service/SaveObject"
	Service_SaveStreamChunk_FullMethodName = "/resource.store.Service/SaveStreamChunk"
	Service_GetObject_FullMethodName       = "/resource.store.Service/GetObject"
	Service_GetStreamChunk_FullMethodName  = "/resource.store.Service/GetStreamChunk"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	SaveObject(ctx context.Context, in *SaveObjectRequest, opts ...grpc.CallOption) (*SaveObjectResponse, error)
	SaveStreamChunk(ctx context.Context, in *SaveStreamChunkRequest, opts ...grpc.CallOption) (*SaveStreamChunkResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
	GetStreamChunk(ctx context.Context, in *GetStreamChunkRequest, opts ...grpc.CallOption) (*GetStreamChunkResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) SaveObject(ctx context.Context, in *SaveObjectRequest, opts ...grpc.CallOption) (*SaveObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveObjectResponse)
	err := c.cc.Invoke(ctx, Service_SaveObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SaveStreamChunk(ctx context.Context, in *SaveStreamChunkRequest, opts ...grpc.CallOption) (*SaveStreamChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveStreamChunkResponse)
	err := c.cc.Invoke(ctx, Service_SaveStreamChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, Service_GetObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetStreamChunk(ctx context.Context, in *GetStreamChunkRequest, opts ...grpc.CallOption) (*GetStreamChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamChunkResponse)
	err := c.cc.Invoke(ctx, Service_GetStreamChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	SaveObject(context.Context, *SaveObjectRequest) (*SaveObjectResponse, error)
	SaveStreamChunk(context.Context, *SaveStreamChunkRequest) (*SaveStreamChunkResponse, error)
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
	GetStreamChunk(context.Context, *GetStreamChunkRequest) (*GetStreamChunkResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) SaveObject(context.Context, *SaveObjectRequest) (*SaveObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveObject not implemented")
}
func (UnimplementedServiceServer) SaveStreamChunk(context.Context, *SaveStreamChunkRequest) (*SaveStreamChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveStreamChunk not implemented")
}
func (UnimplementedServiceServer) GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedServiceServer) GetStreamChunk(context.Context, *GetStreamChunkRequest) (*GetStreamChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamChunk not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_SaveObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SaveObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_SaveObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SaveObject(ctx, req.(*SaveObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SaveStreamChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveStreamChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SaveStreamChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_SaveStreamChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SaveStreamChunk(ctx, req.(*SaveStreamChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetStreamChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetStreamChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetStreamChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetStreamChunk(ctx, req.(*GetStreamChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resource.store.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveObject",
			Handler:    _Service_SaveObject_Handler,
		},
		{
			MethodName: "SaveStreamChunk",
			Handler:    _Service_SaveStreamChunk_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _Service_GetObject_Handler,
		},
		{
			MethodName: "GetStreamChunk",
			Handler:    _Service_GetStreamChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource/store/store.proto",
}
